apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        # The GitHub Action will dynamically update this image tag during deployment
        image: placeholder-image
        ports:
        - containerPort: 3000
